---
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"
    assignees:
      - "fredclausen"

  - package-ecosystem: "docker-compose"
    directory: "/system-linux/acarshub"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 40
    assignees:
      - "fredclausen"

  - package-ecosystem: "docker-compose"
    directory: "/systems-linux/sdrhub"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 40
    assignees:
      - "fredclausen"

  # - package-ecosystem: "docker-compose"
  # directory: "/brandon"
  # schedule:
  #   interval: "daily"
  #   time: "00:00"
  #   timezone: "Etc/UTC"
  # open-pull-requests-limit: 40
  # assignees:
  #   - "fredclausen"

  - package-ecosystem: "docker-compose"
    directory: "/systems-linux/hfdlhub1"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 40
    assignees:
      - "fredclausen"

  - package-ecosystem: "docker-compose"
    directory: "/systems-linux/hfdlhub2"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 40
    assignees:
      - "fredclausen"

  - package-ecosystem: "docker-compose"
    directory: "/systems-linux/vdlmhub"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 40
    assignees:
      - "fredclausen"

  # - package-ecosystem: "docker-compose"
  #   directory: "/vps"
  #   schedule:
  #     interval: "daily"
  #     time: "00:00"
  #     timezone: "Etc/UTC"
  #   open-pull-requests-limit: 40
  #   assignees:
  #     - "fredclausen"
