services:
  dozzle-agent:
    image: amir20/dozzle:v8.14.4
    container_name: dozzle-agent
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007

  dumpvdl2-1:
    #image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:latest-build-387
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:trixie-latest-build-4
    tty: true
    container_name: dumpvdl2-1
    restart: always
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      - TZ=${FEEDER_TZ}
      - SERIAL=00013475
      - FREQUENCIES=136975000;136945000;136925000;136825000;136800000;136775000
      - FEED_ID=CS-KABQ-VDLM
      - VDLM_FILTER_ENABLE=
      - ZMQ_MODE=client
      - ZMQ_ENDPOINT=tcp://192.168.31.20:35555
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /dev:/dev

  dumpvdl2-2:
    #image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:latest-build-387
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:trixie-latest-build-4
    tty: true
    container_name: dumpvdl2-2
    restart: always
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      - TZ=${FEEDER_TZ}
      - SERIAL=00013212
      - FREQUENCIES=136725000;136700000;136675000;136650000;136300000;136100000
      - FEED_ID=CS-KABQ-VDLM
      - VDLM_FILTER_ENABLE=
      - ZMQ_MODE=client
      - ZMQ_ENDPOINT=tcp://192.168.31.20:35555
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /dev:/dev

  dumpvdl2-3:
    #image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:latest-build-387
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:trixie-latest-build-4
    tty: true
    container_name: dumpvdl2-3
    restart: always
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      - TZ=${FEEDER_TZ}
      - SERIAL=00012507
      - FREQUENCIES=131725000;131550000;131125000
      - FEED_ID=CS-KABQ-VDLM
      - VDLM_FILTER_ENABLE=
      - ZMQ_MODE=client
      - ZMQ_ENDPOINT=tcp://192.168.31.20:35555
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /dev:/dev

  dumpvdl2-4:
    #image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:latest-build-387
    image: ghcr.io/sdr-enthusiasts/docker-dumpvdl2:trixie-latest-build-4
    tty: true
    container_name: dumpvdl2-4
    restart: always
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      - TZ=${FEEDER_TZ}
      - SERIAL=00012867
      - FREQUENCIES=130825000;130450000;130025000
      - FEED_ID=CS-KABQ-VDLM
      - VDLM_FILTER_ENABLE=
      - ZMQ_MODE=client
      - ZMQ_ENDPOINT=tcp://192.168.31.20:35555
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /dev:/dev
