---
name: CI (Darwin)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  find-darwin:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.out.outputs.systems }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21

      - id: out
        run: |
          echo "Evaluating darwinConfigurations..."

          systems=$(nix eval --json .#darwinConfigurations --apply builtins.attrNames)

          echo "Darwin systems: $systems"

          if [ "$systems" = "[]" ]; then
            echo "::warning::No darwin systems found!"
          fi

          echo "systems=$systems" >> "$GITHUB_OUTPUT"

  build-darwin:
    runs-on: macos-latest
    needs: find-darwin
    if: ${{ fromJson(needs.find-darwin.outputs.systems).length > 0 }}
    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJson(needs.find-darwin.outputs.systems) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Build Darwin system
        run: |
          echo "Building darwin sys: ${{ matrix.system }}"
          nix build ".#darwinConfigurations.${{ matrix.system }}.system"
