---
name: CI (Darwin)

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  find-darwin:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.out.outputs.systems }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
          use-gha-cache: false

      - id: out
        run: |
          echo "Evaluating darwinConfigurations..."
          systems=$(nix eval --json .#darwinConfigurations --apply builtins.attrNames)
          echo "Darwin systems: $systems"
          echo "systems=$systems" >> "$GITHUB_OUTPUT"

  build-darwin:
    runs-on: macos-latest
    needs: find-darwin
    if: ${{ needs.find-darwin.outputs.systems != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJson(needs.find-darwin.outputs.systems) }}

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
          use-gha-cache: false

      - name: Build Darwin system
        run: |
          echo "Building Darwin system: ${{ matrix.system }}"
          nix build ".#darwinConfigurations.${{ matrix.system }}.system"

  build-darwin-summary:
    runs-on: ubuntu-latest
    needs: build-darwin
    steps:
      - name: Mark servers build summary
        run: |
          echo "All server builds finished."
